package passgen

// words — словарь английских слов длиной 6–10 букв для второй части пароля.
var words = []string{
	"admiral", "almond", "anchor", "antelope", "antenna", "apricot", "archer", "architect",
	"avocado", "badger", "ballad", "banana", "banker", "barber", "basalt", "battery",
	"beacon", "beaver", "binary", "blizzard", "bridge", "broker", "bronze", "buffalo",
	"buffer", "butler", "butter", "button", "buzzard", "cabbage", "cabinet", "candle",
	"canyon", "captain", "caramel", "carrot", "cashew", "castle", "cavern", "charger",
	"cheese", "cheetah", "cherry", "cinder", "cinnamon", "cipher", "circuit", "cobalt",
	"coconut", "coffee", "compass", "cookie", "copper", "cottage", "cotton", "crystal",
	"cursor", "dancer", "decimal", "desert", "diamond", "doctor", "dolphin", "donkey",
	"driver", "drizzle", "drummer", "elephant", "emerald", "emperor", "engine", "engineer",
	"evening", "falcon", "farmer", "feather", "ferret", "flamingo", "forest", "fountain",
	"garden", "garlic", "gazelle", "gearbox", "ginger", "giraffe", "glacier", "glazier",
	"gopher", "granite", "gravel", "guitar", "hamster", "harbor", "harvest", "hedgehog",
	"hermit", "horizon", "hunter", "iguana", "integer", "island", "jaguar", "jasper",
	"kernel", "kestrel", "keyboard", "knight", "lagoon", "lantern", "leather", "legend",
	"lemming", "leopard", "lettuce", "library", "lightning", "lizard", "magnet", "magpie",
	"marble", "market", "marmot", "matrix", "meadow", "meerkat", "melody", "miller",
	"mirror", "module", "mongoose", "monitor", "monkey", "monsoon", "morning", "muffin",
	"muskrat", "needle", "nickel", "noodle", "numbat", "opaline", "orange", "ostrich",
	"otterly", "packet", "painter", "pancake", "panther", "parrot", "pastry", "peacock",
	"peanut", "pebble", "pelican", "penguin", "pepper", "pigeon", "piston", "plateau",
	"pocket", "poetry", "porpoise", "porter", "potato", "potter", "prairie", "printer",
	"pumpkin", "puzzle", "quartz", "rabbit", "raccoon", "radish", "rainbow", "ranger",
	"reindeer", "rhythm", "ribbon", "riddle", "risotto", "rocket", "rooster", "router",
	"saddle", "sailor", "salmon", "sapphire", "scanner", "sculptor", "seagull", "secret",
	"server", "shadow", "signal", "silver", "singer", "socket", "soldier", "sparrow",
	"speaker", "spinach", "squirrel", "starling", "station", "student", "sunrise", "sunset",
	"swallow", "switch", "tailor", "teacher", "temple", "tensor", "thread", "thunder",
	"tomato", "toucan", "trumpet", "tundra", "turbine", "turnip", "turtle", "twilight",
	"valley", "vanilla", "vector", "velvet", "violin", "volcano", "vulture", "waffle",
	"waiter", "walnut", "walrus", "weasel", "weaver", "wizard", "yogurt",
}
