// Package pkgbuild renders the makepkg input files: PKGBUILD, .SRCINFO and
// the optional .INSTALL hook.
package pkgbuild

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// Spec is the fully resolved description of the Arch package to build.
type Spec struct {
	PkgName     string
	PkgVersion  string
	PkgRelease  string
	PkgDesc     string
	Arch        []string
	URL         string
	License     []string
	Depends     []string
	OptDepends  []string
	Conflicts   []string
	Provides    []string
	Replaces    []string
	Maintainer  string
	PostInstall string
	PostRemove  string
	PreInstall  string
	PreRemove   string
}

var invalidNameChars = regexp.MustCompile(`[^a-z0-9@._+-]`)

// SanitizeName converts a Debian package name into a valid pacman pkgname.
func SanitizeName(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	name = invalidNameChars.ReplaceAllString(name, "-")
	name = strings.TrimLeft(name, "-.")
	if name == "" {
		return "converted-package"
	}
	return name
}

var invalidVersionChars = regexp.MustCompile(`[^A-Za-z0-9._]`)

// SanitizeVersion converts a Debian version into a valid pkgver.
func SanitizeVersion(version string) string {
	version = strings.TrimSpace(version)
	version = invalidVersionChars.ReplaceAllString(version, ".")
	version = strings.Trim(version, ".")
	if version == "" {
		return "0"
	}
	return version
}

// ArchFromDebian maps a Debian architecture onto the makepkg arch array.
func ArchFromDebian(arch string) []string {
	switch strings.ToLower(strings.TrimSpace(arch)) {
	case "amd64":
		return []string{"x86_64"}
	case "i386":
		return []string{"i686"}
	case "arm64":
		return []string{"aarch64"}
	case "armhf", "armel":
		return []string{"armv7h"}
	case "all", "any", "":
		return []string{"any"}
	default:
		return []string{arch}
	}
}

// NeedsInstallHook reports whether an .INSTALL file has to be generated.
func (s Spec) NeedsInstallHook() bool {
	return s.PostInstall != "" || s.PostRemove != "" || s.PreInstall != "" || s.PreRemove != ""
}

// Render produces the PKGBUILD contents. The build recipe simply copies the
// already extracted Debian payload into $pkgdir, which keeps the conversion
// reproducible and root-free.
func (s Spec) Render() string {
	var b strings.Builder
	if s.Maintainer != "" {
		fmt.Fprintf(&b, "# Maintainer: %s\n", singleLine(s.Maintainer))
	}
	b.WriteString("# Generated by KUZNICA (https://sd-on.ru) - Debian to Arch Linux converter\n\n")

	fmt.Fprintf(&b, "pkgname=%s\n", SanitizeName(s.PkgName))
	fmt.Fprintf(&b, "pkgver=%s\n", SanitizeVersion(s.PkgVersion))
	fmt.Fprintf(&b, "pkgrel=%s\n", defaultString(s.PkgRelease, "1"))
	fmt.Fprintf(&b, "pkgdesc=%s\n", quote(singleLine(s.PkgDesc)))
	fmt.Fprintf(&b, "arch=%s\n", array(defaultSlice(s.Arch, []string{"any"})))
	if s.URL != "" {
		fmt.Fprintf(&b, "url=%s\n", quote(s.URL))
	}
	fmt.Fprintf(&b, "license=%s\n", array(defaultSlice(s.License, []string{"custom"})))
	if len(s.Depends) > 0 {
		fmt.Fprintf(&b, "depends=%s\n", array(s.Depends))
	}
	if len(s.OptDepends) > 0 {
		fmt.Fprintf(&b, "optdepends=%s\n", array(s.OptDepends))
	}
	if len(s.Conflicts) > 0 {
		fmt.Fprintf(&b, "conflicts=%s\n", array(s.Conflicts))
	}
	if len(s.Provides) > 0 {
		fmt.Fprintf(&b, "provides=%s\n", array(s.Provides))
	}
	if len(s.Replaces) > 0 {
		fmt.Fprintf(&b, "replaces=%s\n", array(s.Replaces))
	}
	b.WriteString("options=(!strip !debug emptydirs)\n")
	if s.NeedsInstallHook() {
		fmt.Fprintf(&b, "install=%s.install\n", SanitizeName(s.PkgName))
	}

	b.WriteString(`
package() {
  # payload/ holds the data.tar contents already extracted by KUZNICA
  cp -a "${startdir}/payload/." "${pkgdir}/"
}
`)
	return b.String()
}

// RenderSRCINFO produces the .SRCINFO metadata matching Render.
func (s Spec) RenderSRCINFO() string {
	var b strings.Builder
	fmt.Fprintf(&b, "pkgbase = %s\n", SanitizeName(s.PkgName))
	fmt.Fprintf(&b, "\tpkgdesc = %s\n", singleLine(s.PkgDesc))
	fmt.Fprintf(&b, "\tpkgver = %s\n", SanitizeVersion(s.PkgVersion))
	fmt.Fprintf(&b, "\tpkgrel = %s\n", defaultString(s.PkgRelease, "1"))
	if s.URL != "" {
		fmt.Fprintf(&b, "\turl = %s\n", s.URL)
	}
	for _, arch := range defaultSlice(s.Arch, []string{"any"}) {
		fmt.Fprintf(&b, "\tarch = %s\n", arch)
	}
	for _, license := range defaultSlice(s.License, []string{"custom"}) {
		fmt.Fprintf(&b, "\tlicense = %s\n", license)
	}
	for _, dep := range s.Depends {
		fmt.Fprintf(&b, "\tdepends = %s\n", dep)
	}
	for _, dep := range s.OptDepends {
		fmt.Fprintf(&b, "\toptdepends = %s\n", dep)
	}
	for _, item := range s.Conflicts {
		fmt.Fprintf(&b, "\tconflicts = %s\n", item)
	}
	for _, item := range s.Provides {
		fmt.Fprintf(&b, "\tprovides = %s\n", item)
	}
	for _, item := range s.Replaces {
		fmt.Fprintf(&b, "\treplaces = %s\n", item)
	}
	fmt.Fprintf(&b, "\npkgname = %s\n", SanitizeName(s.PkgName))
	return b.String()
}

// RenderInstall produces the .INSTALL hook wrapping the Debian maintainer
// scripts. Returns an empty string when no scripts are present.
func (s Spec) RenderInstall() string {
	if !s.NeedsInstallHook() {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Generated by KUZNICA from the Debian maintainer scripts\n")
	writeHook(&b, "pre_install", s.PreInstall)
	writeHook(&b, "post_install", s.PostInstall)
	writeHook(&b, "pre_upgrade", s.PreInstall)
	writeHook(&b, "post_upgrade", s.PostInstall)
	writeHook(&b, "pre_remove", s.PreRemove)
	writeHook(&b, "post_remove", s.PostRemove)
	return b.String()
}

func writeHook(b *strings.Builder, name, body string) {
	if strings.TrimSpace(body) == "" {
		return
	}
	fmt.Fprintf(b, "\n%s() {\n", name)
	for _, line := range strings.Split(strings.TrimRight(body, "\n"), "\n") {
		fmt.Fprintf(b, "  %s\n", line)
	}
	b.WriteString("}\n")
}

func array(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, quote(value))
	}
	return "(" + strings.Join(quoted, " ") + ")"
}

func quote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

func singleLine(value string) string {
	value = strings.ReplaceAll(value, "\n", " ")
	return strings.Join(strings.Fields(value), " ")
}

func defaultString(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func defaultSlice(values, fallback []string) []string {
	if len(values) == 0 {
		return fallback
	}
	out := append([]string(nil), values...)
	sort.Strings(out)
	return out
}
